name: Build and test

on:
  pull_request:
    branches: [ master ]
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bms2csv
        path: |
          bms2csv/bin/Release/net6.0
          
