name: MSBuild

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build with MSBuild
      run: msbuild bms2csv.sln -p:OutDir="out/" /p:Configuration=Release;Platform="Any CPU"
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build-result
        path: ./bms2csv/out/
